# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\CKH\Desktop\PyQt5_Yolo\wait.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wait(object):
    def setupUi(self, Wait):
        Wait.setObjectName("Wait")
        Wait.resize(435, 104)
        Wait.setMinimumSize(QtCore.QSize(435, 104))
        Wait.setMaximumSize(QtCore.QSize(435, 104))
        Wait.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        Wait.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Wait)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 391, 61))
        self.label.setObjectName("label")
        Wait.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Wait)
        self.statusbar.setObjectName("statusbar")
        Wait.setStatusBar(self.statusbar)

        self.retranslateUi(Wait)
        QtCore.QMetaObject.connectSlotsByName(Wait)

    def retranslateUi(self, Wait):
        _translate = QtCore.QCoreApplication.translate
        Wait.setWindowTitle(_translate("Wait", "基于计算机视觉的快递包装废弃物智能分拣机械臂"))
        self.label.setText(_translate("Wait", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">请稍后，正在处理.....</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wait = QtWidgets.QMainWindow()
    ui = Ui_Wait()
    ui.setupUi(Wait)
    Wait.show()
    sys.exit(app.exec_())
